package MessageAuthenticationCode;

import java.security.Key;

public class MACtest {
    public static void main(String args[]) throws Exception {
        //Create key generator
        Kgen kgen = new Kgen();
        //Generate shared key between sender and receiver (it is the same)
        Key k = kgen.generatesKey();

        //Message to send
        String message = new String("Hi how are you");

        //Initialize MAC algorithm
        MacAlgorithm macAlgorithm = new MacAlgorithm(k,message);
        byte[] Tag = macAlgorithm.MacOperation();

        //The receveir use the Verify algorithm and match the tag received by the sender and the tag generated by the receiver
        VerifyAlgorithm verifyAlgorithm = new VerifyAlgorithm(message,k,Tag);
        //Check if the message is authentic
        System.out.println("The message is: "+verifyAlgorithm.checkTagValidity(Tag));

    }
}
